#!/usr/bin/env perl
use lib 'lib';
use Marvin;
use experimental 'signatures';
use IO::Prompt;

my $config=plugin 'Config';
$config->{adapter_config}->{pass} //= prompt('password: ', -e=>'*'); 

plugin 'RT';

app->start;

1;
